name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2019, os: windows-2019 }
        - { name: Windows VS2022, os: windows-2022 }
        - { name: Linux GCC,      os: ubuntu-24.04 }
        - { name: Linux Clang,    os: ubuntu-24.04, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS x64,      os: macos-13 }
        - { name: macOS ARM64,    os: macos-14 }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run:  |
            sudo apt-get update
            sudo apt-get install libfreetype-dev libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

    - name: Lightspeed - Checkout Code
      uses: actions/checkout@v4

    - name: Lightspeed - Configure CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install -DCMAKE_VERBOSE_MAKEFILE=ON ${{matrix.platform.flags}}

    - name: Lightspeed - Build
      shell: bash
      run: cmake --build $GITHUB_WORKSPACE/build --config Release --target install